### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by EspinosaLeal** [ausgerechnet/cwb-ccc#35]
Hi, I've been trying to install cwb-ccc and I think the issue is that cwb-python is not available via pip. I tried to find that library around but not luck, any hint on how to solve this issue?
Thanks in advance!

**Comment by ausgerechnet** [comment]
Hi there!

cwb-python is available on [PyPI](https://pypi.org/project/cwb-python/) but can make problems during installation. I am in contact with its developer and we will fix the issue in a release later this year.

For now, if you cannot install cwb-python with the usual
```
python3 -m pip install cwb-python
```
you can 
1. try installing python3-dev and cython beforehand:
```
sudo apt install python3-dev --upgrade
python3 -m pip install cython --upgrade
python3 -m pip install cwb-python
```
2. download one of the manylinux or macos [wheels](https://pypi.org/project/cwb-python/#files) and then use pip, e.g.
```
python3 -m pip install cwb_python-0.2.2-cp36-cp36m-manylinux1_x86_64.whl 
```
3. clone the cwb-python [repository](https://github.com/fau-klue/cwb-python) here on github and compile the underlying cython code yourself.

I'd be happy if you let me know how it goes and any specifics (OS, python version, error messages)!

**Comment by dokempf** [comment]
I also had massive trouble installing on my machine. Instead, I went for an isolated build in a Docker container that also runs Jupyter. I thought I'd share the result if anyone is interested:

* Dockerfile: https://github.com/dokempf/cwb-ccc/blob/master/Dockerfile
* DockerHub repository: https://hub.docker.com/repository/docker/dkempf/cwb-ccc

To try on your machine you can do (assuming you have Docker):
```
docker run -t -p 8888:8888 dkempf/cwb-ccc:0.9.15
```
and open the shown URL on `http://127.0.0.1:8888` in a browser.

**Comment by ausgerechnet** [comment]
I too have problems myself installing cwb-python if CWB is not installed in the standard location (/usr/local without a separate sub-folder). You can install the CWB in the standard location by opting for the "SITE=standard' in the `config.mk` (instead of the "beta-install" option enabled by default in the SVN trunk).

I like dokempf's approach of running the installation in an isolated container. There's a respective [Dockerfile](https://github.com/ausgerechnet/cwb-ccc/blob/2f4964eaf0a37e115600b7e5d4b25d7c4f39531c/Dockerfile) here on the 0.9.16 branch (without the jupyter notebook).

I also built some wheels for [cwb-python](https://github.com/fau-klue/cwb-python) for python3.7 and python3.8, see the [action artifacts](https://github.com/fau-klue/cwb-python/actions/runs/806949867) in that repo.

Hope that helps for now. I'll give an update once the new wheels of cwb-python have been deployed to PyPI.
