### ISSUE TITLE
access lemma/pos of annotated corpora

### ISSUE THREAD

**Issue by iulusoy** [ausgerechnet/cwb-ccc#44]
It seems not possible to access p-attributes like lemma and pos, ie. for the demo corpus GERMAN-LAW. While it is possible to query lemma/pos through cqp directly using `[lemma="sein"]` or `[pos="NN"]`, with cwb-ccc an error is returned. Following the instructions in the cwb-ccc README,
```
corpus = corpora.activate(corpus_name="GERMAN-LAW")
query = r'"\[" ([word="[A-Z0-9]+.?"%d]+ "/"?)+ "\]"'
dump = corpus.query(query)
dump.concordance(p_show=["word", "lemma"], s_show=["text_id"])
```
The last command returns a `KeyError`.   
Also when listing the corpus attributes through `corpus.attributes_available`, lemma and pos are `False`.

**Comment by ausgerechnet** [comment]
Hi, and thanks for your bug report.

I cannot reproduce the bug, though I am able to reproduce the `KeyError` in your example above, since "text_id" is not an indexed s-attribute in GERMAN-LAW:

<details>
<summary><code>corpus.attributes_available</code></summary>
<p>

| type   | attribute   | annotation   | active   |
|:-------|:------------|:-------------|:---------|
| p-Att  | word        | False        | True     |
| p-Att  | pos         | False        | False    |
| p-Att  | lemma       | False        | False    |
| p-Att  | agr         | False        | False    |
| p-Att  | alemma      | False        | False    |
| s-Att  | gesetz      | False        | False    |
| s-Att  | s           | False        | False    |
| s-Att  | s\_len      | True         | False    |
| s-Att  | cl          | False        | False    |
| s-Att  | cl1         | False        | False    |
| s-Att  | cl\_f       | True         | False    |
| s-Att  | cl\_f1      | True         | False    |
| s-Att  | cl\_h       | True         | False    |
| s-Att  | cl\_h1      | True         | False    |
| s-Att  | cl\_vlem    | True         | False    |
| s-Att  | cl\_vlem1   | True         | False    |
| s-Att  | cl\_len     | True         | False    |
| s-Att  | pp          | False        | False    |
| s-Att  | pp1         | False        | False    |
| s-Att  | pp\_f       | True         | False    |
| s-Att  | pp\_f1      | True         | False    |
| s-Att  | pp\_h       | True         | False    |
| s-Att  | pp\_h1      | True         | False    |
| s-Att  | pp\_agr     | True         | False    |
| s-Att  | pp\_agr1    | True         | False    |
| s-Att  | pp\_len     | True         | False    |
| s-Att  | np          | False        | False    |
| s-Att  | np1         | False        | False    |
| s-Att  | np2         | False        | False    |
| s-Att  | np\_f       | True         | False    |
| s-Att  | np\_f1      | True         | False    |
| s-Att  | np\_f2      | True         | False    |
| s-Att  | np\_h       | True         | False    |
| s-Att  | np\_h1      | True         | False    |
| s-Att  | np\_h2      | True         | False    |
| s-Att  | np\_agr     | True         | False    |
| s-Att  | np\_agr1    | True         | False    |
| s-Att  | np\_agr2    | True         | False    |
| s-Att  | np\_len     | True         | False    |
| s-Att  | ap          | False        | False    |
| s-Att  | ap1         | False        | False    |
| s-Att  | ap\_f       | True         | False    |
| s-Att  | ap\_f1      | True         | False    |
| s-Att  | ap\_h       | True         | False    |
| s-Att  | ap\_h1      | True         | False    |
| s-Att  | ap\_agr     | True         | False    |
| s-Att  | ap\_agr1    | True         | False    |
| s-Att  | ap\_len     | True         | False    |
| s-Att  | advp        | False        | False    |
| s-Att  | advp\_f     | True         | False    |
| s-Att  | advp\_h     | True         | False    |
| s-Att  | advp\_len   | True         | False    |
| s-Att  | vc          | False        | False    |
| s-Att  | vc\_f       | True         | False    |
| s-Att  | vc\_len     | True         | False    |

</p>
</details>
<br/>

Note that column "annotation" shows whether the indexed attribute has additional annotation, which only makes sense for s-attributes (where there's a distinction between unannotated attributes such as `<s>` and annotated attributes such as `<s len="15">`).

Column "active" shows whether the attribute is activated in CQP for direct concordancing; this feature is however not used by cwb-ccc.

In short, your example works without the `s_show=["text_id"]` part:
```
corpus = corpora.activate(corpus_name="GERMAN-LAW")
query = r'"\[" ([word="[A-Z0-9]+.?"%d]+ "/"?)+ "\]"'
dump = corpus.query(query)
```

<details>
<summary><code>dump.concordance(p_show=["word", "lemma"])</code></summary>
<p>

|   *match* |   *matchend* | word                                                                                                                                                                                                                                                                | lemma                                                                                                                                                                                                                                                     |
|----------:|-------------:|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|    675028 |       675030 | soweit nichts anderes bestimmt ist . ( 2 ) Der Antrag steht der öffentlichen Klage gleich . An die Stelle [ 145 ] der Anklageschrift tritt eine Antragsschrift , die den Erfordernissen der Anklageschrift entsprechen muß . In der Antragsschrift ist die Maßregel | soweit nichts ander bestimmen sein . ( @card@ ) d Antrag stehen d öffentlich Klage gleich . an d Stelle [ @card@ ] d Anklageschrift treten ein Antragsschrift , d d Erfordernis d Anklageschrift entsprechen müssen . in d Antragsschrift sein d Maßregel |

</p>
</details>
<br/>

**Comment by iulusoy** [comment]
Thank you, that solves it!
